[package]
name = "willow-application-server-rs"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[dependencies]

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
